
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>


G_BEGIN_DECLS

/* enumerations from "nautilus-info-provider.h" */


GType nautilus_operation_result_get_type (void);
#define NAUTILUS_TYPE_OPERATION_RESULT (nautilus_operation_result_get_type())

G_END_DECLS

/* Generated data ends here */

