
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef GEXIV2_ENUMS_H
#define GEXIV2_ENUMS_H

#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from gexiv2-log.h */
GType gexiv2_gexiv2_log_level_get_type (void);
#define GEXIV2_TYPE_GEXIV2_LOG_LEVEL (gexiv2_gexiv2_log_level_get_type())
/* enumerations from gexiv2-metadata.h */
GType gexiv2_gexiv2_orientation_get_type (void);
#define GEXIV2_TYPE_GEXIV2_ORIENTATION (gexiv2_gexiv2_orientation_get_type())
GType gexiv2_gexiv2_structure_type_get_type (void);
#define GEXIV2_TYPE_GEXIV2_STRUCTURE_TYPE (gexiv2_gexiv2_structure_type_get_type())
GType gexiv2_gexiv2_xmp_format_flags_get_type (void);
#define GEXIV2_TYPE_GEXIV2_XMP_FORMAT_FLAGS (gexiv2_gexiv2_xmp_format_flags_get_type())
GType gexiv2_gexiv2_byte_order_get_type (void);
#define GEXIV2_TYPE_GEXIV2_BYTE_ORDER (gexiv2_gexiv2_byte_order_get_type())
G_END_DECLS

#endif /* GEXIV2_ENUMS_H */

/* Generated data ends here */

