
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#ifndef __TRACKER_ENUMS_TYPES_H__
#define __TRACKER_ENUMS_TYPES_H__

#include <glib-object.h>
#include "tracker-enums.h"

G_BEGIN_DECLS

/* enumerations from "tracker-enums.h" */
GType tracker_serialization_format_get_type (void) G_GNUC_CONST;
#define TRACKER_TYPE_SERIALIZATION_FORMAT (tracker_serialization_format_get_type ())
GType tracker_index_location_flags_get_type (void) G_GNUC_CONST;
#define TRACKER_TYPE_INDEX_LOCATION_FLAGS (tracker_index_location_flags_get_type ())
G_END_DECLS

#endif /* __TRACKER_ENUMS_TYPES_H__ */

/* Generated data ends here */

